// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer valores do .env. Mantém fallback para compatibilidade.
const ENV_DEFAULT_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const ENV_DEFAULT_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const ASF_URL = import.meta.env.VITE_SUPABASE_ASF_URL as string | undefined;
const ASF_KEY = import.meta.env.VITE_SUPABASE_ASF_ANON_KEY as string | undefined;

const SUPABASE_URL = ENV_DEFAULT_URL || ASF_URL || '';
const SUPABASE_PUBLISHABLE_KEY = ENV_DEFAULT_KEY || ASF_KEY || '';

// Export function to create Supabase clients dynamically
export const createSupabaseClient = (url: string, anonKey: string, storageKey?: string) => {
  return createClient<Database>(url, anonKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      storageKey,
    },
  });
};

// Default client (for backward compatibility)
export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createSupabaseClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, 'sb-asf')
  : createSupabaseClient('http://localhost', 'invalid-key', 'sb-asf');