// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer valores do .env. Mantém fallback para compatibilidade.
const ENV_DEFAULT_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const ENV_DEFAULT_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const ASF_URL = import.meta.env.VITE_SUPABASE_ASF_URL as string | undefined;
const ASF_KEY = import.meta.env.VITE_SUPABASE_ASF_ANON_KEY as string | undefined;

const SUPABASE_URL = ENV_DEFAULT_URL || ASF_URL || '';
const SUPABASE_PUBLISHABLE_KEY = ENV_DEFAULT_KEY || ASF_KEY || '';

// Cache para evitar múltiplas instâncias
const clientCache = new Map<string, ReturnType<typeof createClient<Database>>>();

// Export function to create Supabase clients dynamically
export const createSupabaseClient = (url: string, anonKey: string, storageKey: string = 'sb-auth-token') => {
  const cacheKey = `${url}-${anonKey}-${storageKey}`;
  
  // Retornar instância em cache se existir
  if (clientCache.has(cacheKey)) {
    return clientCache.get(cacheKey)!;
  }
  
  const client = createClient<Database>(url, anonKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      storageKey,
    },
  });
  
  clientCache.set(cacheKey, client);
  return client;
};

// Default client (for backward compatibility)
export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createSupabaseClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, 'sb-asf')
  : createSupabaseClient('http://localhost', 'invalid-key', 'sb-asf');